title: Federica Donald | Product Manager
description: Portfolio of work
baseurl: ""
url: "https://fedtried.github.io"
author: "Federica Donald"

# Collections for projects
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap